# Generated by Django 3.2.25 on 2025-04-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250405_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('customer', 'Customer')], max_length=20, unique=True),
        ),
    ]
